##In this assignment you are requested to predict the price of a vehicle given it's features.


1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go

In [2]:
cars_df = pd.read_csv('https://raw.githubusercontent.com/ShaiShmuel/BigData/master/DataSets/cars.csv')
cars_df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [3]:
cars_df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [4]:
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

In [ ]:
print(cars_df.shape[0])
print("X")
print(cars_df.shape[1])

205
X
26

In [5]:
cars_df.isna().sum() ## no missing ##

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [6]:
cars_df.nunique()

car_ID              205
symboling             6
CarName             147
fueltype              2
aspiration            2
doornumber            2
carbody               5
drivewheel            3
enginelocation        2
wheelbase            53
carlength            75
carwidth             44
carheight            49
curbweight          171
enginetype            7
cylindernumber        7
enginesize           44
fuelsystem            8
boreratio            38
stroke               37
compressionratio     32
horsepower           59
peakrpm              23
citympg              29
highwaympg           30
price               189
dtype: int64

In [7]:
cars_df.drop(axis=1, columns=['car_ID'], inplace=True)
cars_df.drop(axis=1, columns=['CarName'], inplace=True)
cars_df

,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,-1,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,-1,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,-1,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,-1,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [8]:
cars_df.columns = ['symboling','is_gas', 'is_turbo', 'is_four_door', 'carbody', 'drivewheel',
       'is_front_engine', 'wheelbase', 'carlength', 'carwidth', 'carheight',
       'curbweight', 'enginetype', 'cylindernumber', 'enginesize',
       'fuelsystem', 'boreratio', 'stroke', 'compressionratio', 'horsepower',
       'peakrpm', 'citympg', 'highwaympg', 'price']
cars_df.is_gas.replace({'gas':1, 'diesel':0}, inplace=True)
cars_df.is_turbo.replace({'turbo':1, 'std':0}, inplace=True)
cars_df.is_four_door.replace({'four':1, 'two':0}, inplace=True)
cars_df.is_front_engine.replace({'front':1, 'back':0}, inplace=True)
cars_df

,symboling,is_gas,is_turbo,is_four_door,carbody,drivewheel,is_front_engine,wheelbase,carlength,carwidth,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,1,0,0,convertible,rwd,1,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,1,0,0,convertible,rwd,1,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,1,0,0,hatchback,rwd,1,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,1,0,1,sedan,fwd,1,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,1,0,1,sedan,4wd,1,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,1,0,1,sedan,rwd,1,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,-1,1,1,1,sedan,rwd,1,109.1,188.8,68.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,-1,1,0,1,sedan,rwd,1,109.1,188.8,68.9,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,-1,0,1,1,sedan,rwd,1,109.1,188.8,68.9,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,-1,1,1,1,sedan,rwd,1,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [9]:
cars_df.cylindernumber.replace({'four':4, 'six':6, 'three':3, 'twelve':12, 'two':2, 'eight':8, 'five':5},inplace=True)

In [13]:
cars_df.drop('carbody', axis=1, inplace = True)
cars_df.drop('drivewheel', axis=1, inplace = True)
cars_df.drop('enginetype', axis=1, inplace = True)
cars_df.drop('fuelsystem', axis=1, inplace = True)

In [14]:
pd.set_option("display.precision", 3)
corr_df = cars_df.corr()
corr_df

,symboling,is_gas,is_turbo,is_four_door,wheelbase,carlength,carwidth,carheight,curbweight,cylindernumber,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
symboling,1.000,0.194,-0.060,-0.664,-0.532,-0.358,-0.233,-0.541,-0.228,-0.113,-0.106,-0.130,-0.009,-0.179,0.071,0.274,-0.036,0.035,-0.080
is_gas,0.194,1.000,-0.401,-0.191,-0.308,-0.213,-0.234,-0.285,-0.217,0.025,-0.070,-0.054,-0.242,-0.984,0.164,0.477,-0.256,-0.191,-0.106
is_turbo,-0.060,-0.401,1.000,0.032,0.258,0.235,0.301,0.087,0.325,-0.048,0.108,0.213,0.223,0.296,0.242,-0.183,-0.202,-0.254,0.178
is_four_door,-0.664,-0.191,0.032,1.000,0.447,0.399,0.207,0.552,0.197,-0.016,0.021,0.119,-0.011,0.178,-0.127,-0.248,-0.012,-0.036,0.032
wheelbase,-0.532,-0.308,0.258,0.447,1.000,0.875,0.795,0.589,0.776,0.340,0.569,0.489,0.161,0.250,0.353,-0.360,-0.470,-0.544,0.578
carlength,-0.358,-0.213,0.235,0.399,0.875,1.000,0.841,0.491,0.878,0.431,0.683,0.606,0.130,0.158,0.553,-0.287,-0.671,-0.705,0.683
carwidth,-0.233,-0.234,0.301,0.207,0.795,0.841,1.000,0.279,0.867,0.545,0.735,0.559,0.183,0.181,0.641,-0.220,-0.643,-0.677,0.759
carheight,-0.541,-0.285,0.087,0.552,0.589,0.491,0.279,1.000,0.296,-0.014,0.067,0.171,-0.055,0.261,-0.109,-0.320,-0.049,-0.107,0.119
curbweight,-0.228,-0.217,0.325,0.197,0.776,0.878,0.867,0.296,1.000,0.610,0.851,0.648,0.169,0.151,0.751,-0.266,-0.757,-0.797,0.835
cylindernumber,-0.113,0.025,-0.048,-0.016,0.340,0.431,0.545,-0.014,0.610,1.000,0.846,0.231,0.008,-0.020,0.692,-0.124,-0.446,-0.467,0.718
enginesize,-0.106,-0.070,0.108,0.021,0.569,0.683,0.735,0.067,0.851,0.846,1.000,0.584,0.203,0.029,0.810,-0.245,-0.654,-0.677,0.874
boreratio,-0.130,-0.054,0.213,0.119,0.489,0.606,0.559,0.171,0.648,0.231,0.584,1.000,-0.056,0.005,0.574,-0.255,-0.585,-0.587,0.553
stroke,-0.009,-0.242,0.223,-0.011,0.161,0.130,0.183,-0.055,0.169,0.008,0.203,-0.056,1.000,0.186,0.081,-0.068,-0.042,-0.044,0.079
compressionratio,-0.179,-0.984,0.296,0.178,0.250,0.158,0.181,0.261,0.151,-0.020,0.029,0.005,0.186,1.000,-0.204,-0.436,0.325,0.265,0.068
horsepower,0.071,0.164,0.242,-0.127,0.353,0.553,0.641,-0.109,0.751,0.692,0.810,0.574,0.081,-0.204,1.000,0.131,-0.801,-0.771,0.808
peakrpm,0.274,0.477,-0.183,-0.248,-0.360,-0.287,-0.220,-0.320,-0.266,-0.124,-0.245,-0.255,-0.068,-0.436,0.131,1.000,-0.114,-0.054,-0.085
citympg,-0.036,-0.256,-0.202,-0.012,-0.470,-0.671,-0.643,-0.049,-0.757,-0.446,-0.654,-0.585,-0.042,0.325,-0.801,-0.114,1.000,0.971,-0.686
highwaympg,0.035,-0.191,-0.254,-0.036,-0.544,-0.705,-0.677,-0.107,-0.797,-0.467,-0.677,-0.587,-0.044,0.265,-0.771,-0.054,0.971,1.000,-0.698
price,-0.080,-0.106,0.178,0.032,0.578,0.683,0.759,0.119,0.835,0.718,0.874,0.553,0.079,0.068,0.808,-0.085,-0.686,-0.698,1.000

In [15]:
fig = go.Figure()
fig.add_traces(go.Heatmap(
    z=corr_df, 
    x=corr_df.columns, 
    y=corr_df.columns,
    zmax=1, 
    zmin=-1
))
fig.update_layout({
    'title':"cars_df corr heatmap"
})

In [16]:
for i in range(len(corr_df.columns)-1):
  print(corr_df.columns[i], 'is correlated to: ')
  for j in range(len(corr_df.columns)-1):
    if abs(corr_df.iloc[i,j])>=0.85 and i is not j:
      print(corr_df.columns[j], end=', ')
  print('\n----------------------')

symboling is correlated to:

----------------------
is_gas is correlated to:
compressionratio,
----------------------
is_turbo is correlated to:

----------------------
is_four_door is correlated to:

----------------------
wheelbase is correlated to:
carlength,
----------------------
carlength is correlated to:
wheelbase, curbweight,
----------------------
carwidth is correlated to:
curbweight,
----------------------
carheight is correlated to:

----------------------
curbweight is correlated to:
carlength, carwidth, enginesize,
----------------------
cylindernumber is correlated to:

----------------------
enginesize is correlated to:
curbweight,
----------------------
boreratio is correlated to:

----------------------
stroke is correlated to:

----------------------
compressionratio is correlated to:
is_gas,
----------------------
horsepower is correlated to:

----------------------
peakrpm is correlated to:

----------------------
citympg is correlated to:
highwaympg,
----------------------
highwaympg is correlated to:
citympg,
----------------------

In [17]:
cars_df.drop('highwaympg', axis=1, inplace = True)
cars_df.drop('compressionratio', axis=1, inplace = True)
cars_df.drop('wheelbase', axis=1, inplace = True)
cars_df.drop('curbweight', axis=1, inplace = True)

In [18]:
corr_df = cars_df.corr()['price'] # creates new correlation df, and keeps only the 'priceK' column
corr_df = corr_df.iloc[0:-1] # drop the last line, because we dont need the correlation between 'priceK' and 'priceK' (that will be 1)
correlated = corr_df.loc[abs(corr_df)>0.66] # abs() returns absolute value. and using loc[] we can slice rows with values that are greater then 0.66
correlated

carlength         0.683
carwidth          0.759
cylindernumber    0.718
enginesize        0.874
horsepower        0.808
citympg          -0.686
Name: price, dtype: float64

In [19]:
from sklearn.model_selection import train_test_split
X=cars_df[['enginesize']]
y=cars_df.price

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1234)
train_df=pd.merge(left=X_train, right=y_train, left_index=True, right_index=True)
test_df=pd.merge(left=X_train, right=y_train, left_index=True, right_index=True)
train_df.head(10)

     enginesize    price
144         108   9233.0
197         141  16515.0
27           98   8558.0
99          120   8949.0
129         203  31400.5
49          326  36000.0
83          156  14869.0
61          122  10595.0
192          97  13845.0
88          110   9279.0

In [20]:
fig = go.Figure()
fig.add_trace(go.Box(name='enginesize outliers', y=train_df.enginesize))
fig.show()

In [21]:
from sklearn.preprocessing import StandardScaler
x_train_scaler = StandardScaler()
x_test_scaler = StandardScaler()
y_train_scaler = StandardScaler()
y_test_scaler = StandardScaler()

X_train_scaled = x_train_scaler.fit_transform(train_df[['enginesize']])
X_test_scaled = x_test_scaler.fit_transform(test_df[['enginesize']])
y_train_scaled = y_train_scaler.fit_transform(train_df[['price']])
y_test_scaled = y_test_scaler.fit_transform(test_df[['price']])

In [22]:
from sklearn.linear_model import LinearRegression
#define model
lm = LinearRegression()
lm.fit(X_train_scaled,y_train_scaled)
slope = lm.coef_[0]
intercept = lm.intercept_
print('Coefficients: \n', "slope =", slope , ",  Intercept=",intercept,"\n" )
print("The regression equation is:" ,"Price = [" ,intercept,"] + [",slope,"] * curbweight")

Coefficients:
 slope = [0.87796312] ,  Intercept= [4.17663669e-17]

The regression equation is: Price = [ [4.17663669e-17] ] + [ [0.87796312] ] * curbweight

In [23]:
#use lm.predict(X_train) for all the X data from the train set
price_by_train=lm.predict(X_train_scaled)
fitted_price_train= y_train_scaler.inverse_transform(price_by_train)
predicted_train_price =round(pd.Series(fitted_price_train[:,0],index=X_train.index,name='Predicted_train_price'),ndigits=2)
train_df=pd.merge(left=train_df,right=predicted_train_price,left_index=True,right_index=True)
train_df.head(10)

     enginesize    price  Predicted_train_price
144         108   9233.0               10046.09
197         141  16515.0               15625.04
27           98   8558.0                8355.49
99          120   8949.0               12074.80
129         203  31400.5               26106.72
49          326  36000.0               46901.02
83          156  14869.0               18160.93
61          122  10595.0               12412.92
192          97  13845.0                8186.43
88          110   9279.0               10384.21

In [25]:
price_by_test=lm.predict(X_test_scaled)
fitted_price_test= y_test_scaler.inverse_transform(price_by_test)
predicted_test_price = round(pd.Series(fitted_price_test[:,0],index=X_train.index,name='Predicted_test_price'),ndigits=2)
test_df=pd.merge(left=test_df,right=predicted_test_price,left_index=True ,right_index=True)
test_df

     enginesize    price  Predicted_test_price
144         108   9233.0              10046.09
197         141  16515.0              15625.04
27           98   8558.0               8355.49
99          120   8949.0              12074.80
129         203  31400.5              26106.72
..          ...      ...                   ...
152          92   6488.0               7341.14
116         152  17950.0              17484.70
53           91   6695.0               7172.08
38          110   9095.0              10384.21
47          258  32250.0              35404.99

[143 rows x 3 columns]

In [27]:
#1 Cost functions
from sklearn import metrics
print("MSE:",metrics.mean_squared_error(train_df.price, train_df.Predicted_train_price))
print("RMSE:",np.sqrt(metrics.mean_squared_error(train_df.price, train_df.Predicted_train_price)))
print("MAE:",metrics.mean_absolute_error(train_df.price, train_df.Predicted_train_price))

MSE: 14802563.09657832
RMSE: 3847.4099205281364
MAE: 2729.6537762237763

In [28]:
from sklearn.metrics import r2_score
r2_score(train_df.price, train_df.Predicted_train_price)

0.7708192385891866

In [29]:
r2_score(test_df.price, test_df.Predicted_test_price)

0.7708192385891866